### ISSUE TITLE
Request for a up-to-date example design

### ISSUE THREAD

**Issue by mksit** [fpgasystems/fpga-network-stack#20]
Hi,

I would like to use the TCP/IP stack for VCU1525 and need an example design for a test. However, the top-level module (tcp_ip_top) has not been updated with the implementation of the network stack module. 

Is it possible to have an updated and simple example design with basic applications like an echo server?

Best

**Comment by chipet** [comment]
Hi,
The tcp-level module (tcp_ip_top) has not been further updated because we have integrated it within davos framework (https://github.com/fpgasystems/davos). 
If you want an example design project, then I suggest you to use davos, with network stack as a submodule. 
The framework does not support VCU1525.
